export enum ContentType {
  JSON = "application/json",
  HTML = "text/html",
  XML = "application/xml",
  TEXT = "text/plain",
  FORM_URLENCODED = "application/x-www-form-urlencoded",
  FORM_DATA = "multipart/form-data",
  PDF = "application/pdf",
  ZIP = "application/zip",
  PNG = "image/png",
  JPEG = "image/jpeg",
  GIF = "image/gif",
  WEBP = "image/webp",
  SVG = "image/svg+xml",
  MP3 = "audio/mpeg",
  MP4 = "video/mp4",
  WEBM = "video/webm",
  CSV = "text/csv",
  YAML = "application/x-yaml",
}
